Random Experimentation

In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
import pandas as pd
import numpy as np
import unittest
import sys
from sklearn.datasets import fetch_california_housing

sys.path.insert(0, '..')

from src.data import load_california_housing_data
from src.normal_equation import *

In [12]:
cali_df_split = load_california_housing_data()
X_w_int = add_intercept_column(cali_df_split.X)
# beta_hat = fit_using_normal_equation(X_w_int, cali_df_split.y)

In [13]:
X_w_int.shape[1]

9

In [11]:
cali_df_split.X.shape

(20640, 8)

In [19]:
def _validate_normal_equation_inputs(X: pd.DataFrame, y: pd.Series):
    
    #X has the same number of rows as y
    if len(X) != len(y):
        raise ValueError("X and y have different lengths")

    #Neither x nor y has missing values
    if X.isna().any(axis = None):
        raise ValueError("X has at least 1 missing value")
    
    if y.isna().any():
        raise ValueError("y has at least 1 missing value")

    #If x has a single columm, it has to have at least one non-zero value
    if X.shape[1] == 1:
        if not X.any().item():
            raise ValueError("If X has a single column, it must have at least 1 non-zero value")

def fit_using_normal_equation(X: pd.DataFrame, y: pd.Series) -> pd.DataFrame:
    
    _validate_normal_equation_inputs(X, y)

    #reshape
    X = np.array(X) #type: ignore
    y = np.array(y) #type: ignore

    X_t = X.T
    beta_hat = np.linalg.solve(X_t @ X, X_t @ y)

    return pd.DataFrame(beta_hat)


def _validate_predict_using_lin_reg_inputs(X: pd.DataFrame, beta_hat: pd.DataFrame):

    #X has the same number of columns as beta_hat does rows
    if X.shape[1] != beta_hat.shape[0]:
        raise ValueError(f"X has {X.shape[1]} columns while beta_hat has {beta_hat.shape[0]} rows")

    #beta_hat isn't 0d
    if len(beta_hat.shape) == 1:
        raise ValueError("Beta_hat cannot be 0d")

    #beta_hat has 1 column
    if beta_hat.shape[1] != 1:
        raise ValueError(f"Beta_hat must have 1 column. It has {beta_hat.shape[1]}")
    

def predict_using_lin_reg(X: pd.DataFrame, beta_hat: pd.DataFrame):
    """
    Multiply coefficients by feature matrix to generate predictions
    """

    _validate_predict_using_lin_reg_inputs(X, beta_hat)

    print(X.shape)
    print(beta_hat.shape)

    print(type(X))
    print(type(beta_hat))

    preds = X @ beta_hat

    return preds

In [16]:
X_w_int.shape

(20640, 9)

In [22]:
X_w_int

,Intercept,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,1,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,1,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,1,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,1,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...,...
20635,1,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,1,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,1,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
#should not use dataframes for matrix multiplication because pandas wants the column label of the left
#df to match the index label of the right

In [17]:
beta_hat.shape

(9, 1)

In [21]:
beta_hat

           0
0 -36.941920
1   0.436693
2   0.009436
3  -0.107322
4   0.645066
5  -0.000004
6  -0.003787
7  -0.421314
8  -0.434514

In [20]:
preds = predict_using_lin_reg(X_w_int, beta_hat)

preds

(20640, 9)
(9, 1)
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

ValueError: matrices are not aligned